# Generated by Django 3.1.7 on 2021-05-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('admin_id', models.CharField(max_length=10, null=True, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('party_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateField(blank=True)),
                ('region_id', models.CharField(blank=True, max_length=200)),
                ('winner_id', models.CharField(blank=True, max_length=200)),
                ('winner_name', models.CharField(blank=True, max_length=200)),
                ('winner_party', models.CharField(blank=True, max_length=200)),
                ('votes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200, null=True)),
                ('region_id', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('father_name', models.CharField(max_length=200, null=True)),
                ('aadhar_no', models.CharField(max_length=20, null=True, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200, null=True)),
                ('voter_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('vote', models.CharField(blank=True, max_length=200)),
                ('election', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(max_length=50, null=True)),
                ('admin', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.admin')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(blank=True, max_length=200)),
                ('region_id', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('winner', models.CharField(blank=True, max_length=200)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.admin')),
                ('candidates', models.ManyToManyField(to='accounts.Candidate')),
                ('region_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region'),
        ),
        migrations.AddField(
            model_name='admin',
            name='region',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.region'),
        ),
    ]
